globals = {
    "debugstack",
    "gsub",
    "BlizzardOptionsPanel_Slider_Disable",
    "BlizzardOptionsPanel_Slider_Enable",
    "CreateFrame",
    "GetServerTime",
    "GetTime",
    "DEFAULT_CHAT_FRAME",
    "GameFontNormal",
    "GetAddOnMetadata",
    "GetPlayerInfoByGUID",
    "UnitFullName",
    "UIParent",
    "UIDropDownMenu_AddButton",
    "UIDropDownMenu_CreateInfo",
    "UIDropDownMenu_Initialize",
    "UIDropDownMenu_JustifyText",
    "UIDropDownMenu_SetSelectedID",
    "UIDropDownMenu_SetText",
    "UIDropDownMenu_SetWidth",
    "UnitGUID",
    "Realms",
    "RealmIdsByName",
    "GetPhysicalScreenSize",
    "WorldFrame",
    "wipe",
    "C_CVar",
    "GetCVar",
    "Minimap",
}
max_line_length = 132
ignore = {
    "211/_.*",
    "212/_.*",
}
self=false
