-- Realm list generated on Thu Jul  4 23:34:46 UTC 2019
-- by https://github.com/mooreatv/WowApiClient
-- go run realmlist.go -lua > Realms.lua
Realms = {
  [1] = {"Lightbringer", "us"}, -- "Lightbringer", lightbringer
  [2] = {"Cenarius", "us"}, -- "Cenarius", cenarius
  [3] = {"Uther", "us"}, -- "Uther", uther
  [4] = {"Kilrogg", "us"}, -- "Kilrogg", kilrogg
  [5] = {"Proudmoore", "us"}, -- "Proudmoore", proudmoore
  [6] = {"Hyjal", "us"}, -- "Hyjal", hyjal
  [7] = {"Frostwolf", "us"}, -- "Frostwolf", frostwolf
  [8] = {"Ner'zhul", "us"}, -- "Ner'zhul", nerzhul
  [9] = {"Kil'jaeden", "us"}, -- "Kil'jaeden", kiljaeden
  [10] = {"Blackrock", "us"}, -- "Blackrock", blackrock
  [11] = {"Tichondrius", "us"}, -- "Tichondrius", tichondrius
  [12] = {"Silver Hand", "us"}, -- "Silver Hand", silver-hand
  [13] = {"Doomhammer", "us"}, -- "Doomhammer", doomhammer
  [14] = {"Icecrown", "us"}, -- "Icecrown", icecrown
  [15] = {"Deathwing", "us"}, -- "Deathwing", deathwing
  [16] = {"Kel'Thuzad", "us"}, -- "Kel'Thuzad", kelthuzad
  [47] = {"Eitrigg", "us"}, -- "Eitrigg", eitrigg
  [51] = {"Garona", "us"}, -- "Garona", garona
  [52] = {"Alleria", "us"}, -- "Alleria", alleria
  [53] = {"Hellscream", "us"}, -- "Hellscream", hellscream
  [54] = {"Blackhand", "us"}, -- "Blackhand", blackhand
  [55] = {"Whisperwind", "us"}, -- "Whisperwind", whisperwind
  [56] = {"Archimonde", "us"}, -- "Archimonde", archimonde
  [57] = {"Illidan", "us"}, -- "Illidan", illidan
  [58] = {"Stormreaver", "us"}, -- "Stormreaver", stormreaver
  [59] = {"Mal'Ganis", "us"}, -- "Mal'Ganis", malganis
  [60] = {"Stormrage", "us"}, -- "Stormrage", stormrage
  [61] = {"Zul'jin", "us"}, -- "Zul'jin", zuljin
  [62] = {"Medivh", "us"}, -- "Medivh", medivh
  [63] = {"Durotan", "us"}, -- "Durotan", durotan
  [64] = {"Bloodhoof", "us"}, -- "Bloodhoof", bloodhoof
  [65] = {"Khadgar", "us"}, -- "Khadgar", khadgar
  [66] = {"Dalaran", "us"}, -- "Dalaran", dalaran
  [67] = {"Elune", "us"}, -- "Elune", elune
  [68] = {"Lothar", "us"}, -- "Lothar", lothar
  [69] = {"Arthas", "us"}, -- "Arthas", arthas
  [70] = {"Mannoroth", "us"}, -- "Mannoroth", mannoroth
  [71] = {"Warsong", "us"}, -- "Warsong", warsong
  [72] = {"Shattered Hand", "us"}, -- "Shattered Hand", shattered-hand
  [73] = {"Bleeding Hollow", "us"}, -- "Bleeding Hollow", bleeding-hollow
  [74] = {"Skullcrusher", "us"}, -- "Skullcrusher", skullcrusher
  [75] = {"Argent Dawn", "us"}, -- "Argent Dawn", argent-dawn
  [76] = {"Sargeras", "us"}, -- "Sargeras", sargeras
  [77] = {"Azgalor", "us"}, -- "Azgalor", azgalor
  [78] = {"Magtheridon", "us"}, -- "Magtheridon", magtheridon
  [79] = {"Destromath", "us"}, -- "Destromath", destromath
  [80] = {"Gorgonnash", "us"}, -- "Gorgonnash", gorgonnash
  [81] = {"Dethecus", "us"}, -- "Dethecus", dethecus
  [82] = {"Spinebreaker", "us"}, -- "Spinebreaker", spinebreaker
  [83] = {"Bonechewer", "us"}, -- "Bonechewer", bonechewer
  [84] = {"Dragonmaw", "us"}, -- "Dragonmaw", dragonmaw
  [85] = {"Shadowsong", "us"}, -- "Shadowsong", shadowsong
  [86] = {"Silvermoon", "us"}, -- "Silvermoon", silvermoon
  [87] = {"Windrunner", "us"}, -- "Windrunner", windrunner
  [88] = {"Cenarion Circle", "us"}, -- "Cenarion Circle", cenarion-circle
  [89] = {"Nathrezim", "us"}, -- "Nathrezim", nathrezim
  [90] = {"Terenas", "us"}, -- "Terenas", terenas
  [91] = {"Burning Blade", "us"}, -- "Burning Blade", burning-blade
  [92] = {"Gorefiend", "us"}, -- "Gorefiend", gorefiend
  [93] = {"Eredar", "us"}, -- "Eredar", eredar
  [94] = {"Shadowmoon", "us"}, -- "Shadowmoon", shadowmoon
  [95] = {"Lightning's Blade", "us"}, -- "Lightning's Blade", lightnings-blade
  [96] = {"Eonar", "us"}, -- "Eonar", eonar
  [97] = {"Gilneas", "us"}, -- "Gilneas", gilneas
  [98] = {"Kargath", "us"}, -- "Kargath", kargath
  [99] = {"Llane", "us"}, -- "Llane", llane
  [100] = {"Earthen Ring", "us"}, -- "Earthen Ring", earthen-ring
  [101] = {"Laughing Skull", "us"}, -- "Laughing Skull", laughing-skull
  [102] = {"Burning Legion", "us"}, -- "Burning Legion", burning-legion
  [103] = {"Thunderlord", "us"}, -- "Thunderlord", thunderlord
  [104] = {"Malygos", "us"}, -- "Malygos", malygos
  [105] = {"Thunderhorn", "us"}, -- "Thunderhorn", thunderhorn
  [106] = {"Aggramar", "us"}, -- "Aggramar", aggramar
  [107] = {"Crushridge", "us"}, -- "Crushridge", crushridge
  [108] = {"Stonemaul", "us"}, -- "Stonemaul", stonemaul
  [109] = {"Daggerspine", "us"}, -- "Daggerspine", daggerspine
  [110] = {"Stormscale", "us"}, -- "Stormscale", stormscale
  [111] = {"Dunemaul", "us"}, -- "Dunemaul", dunemaul
  [112] = {"Boulderfist", "us"}, -- "Boulderfist", boulderfist
  [113] = {"Suramar", "us"}, -- "Suramar", suramar
  [114] = {"Dragonblight", "us"}, -- "Dragonblight", dragonblight
  [115] = {"Draenor", "us"}, -- "Draenor", draenor
  [116] = {"Uldum", "us"}, -- "Uldum", uldum
  [117] = {"Bronzebeard", "us"}, -- "Bronzebeard", bronzebeard
  [118] = {"Feathermoon", "us"}, -- "Feathermoon", feathermoon
  [119] = {"Bloodscalp", "us"}, -- "Bloodscalp", bloodscalp
  [120] = {"Darkspear", "us"}, -- "Darkspear", darkspear
  [121] = {"Azjol-Nerub", "us"}, -- "Azjol-Nerub", azjolnerub
  [122] = {"Perenolde", "us"}, -- "Perenolde", perenolde
  [123] = {"Eldre'Thalas", "us"}, -- "Eldre'Thalas", eldrethalas
  [124] = {"Spirestone", "us"}, -- "Spirestone", spirestone
  [125] = {"Shadow Council", "us"}, -- "Shadow Council", shadow-council
  [126] = {"Scarlet Crusade", "us"}, -- "Scarlet Crusade", scarlet-crusade
  [127] = {"Firetree", "us"}, -- "Firetree", firetree
  [128] = {"Frostmane", "us"}, -- "Frostmane", frostmane
  [129] = {"Gurubashi", "us"}, -- "Gurubashi", gurubashi
  [130] = {"Smolderthorn", "us"}, -- "Smolderthorn", smolderthorn
  [131] = {"Skywall", "us"}, -- "Skywall", skywall
  [151] = {"Runetotem", "us"}, -- "Runetotem", runetotem
  [153] = {"Moonrunner", "us"}, -- "Moonrunner", moonrunner
  [154] = {"Detheroc", "us"}, -- "Detheroc", detheroc
  [155] = {"Kalecgos", "us"}, -- "Kalecgos", kalecgos
  [156] = {"Ursin", "us"}, -- "Ursin", ursin
  [157] = {"Dark Iron", "us"}, -- "Dark Iron", dark-iron
  [158] = {"Greymane", "us"}, -- "Greymane", greymane
  [159] = {"Wildhammer", "us"}, -- "Wildhammer", wildhammer
  [160] = {"Staghelm", "us"}, -- "Staghelm", staghelm
  [162] = {"Emerald Dream", "us"}, -- "Emerald Dream", emerald-dream
  [163] = {"Maelstrom", "us"}, -- "Maelstrom", maelstrom
  [164] = {"Twisting Nether", "us"}, -- "Twisting Nether", twisting-nether
  [201] = {"불타는 군단", "kr"}, -- "Burning Legion", burning-legion
  [205] = {"아즈샤라", "kr"}, -- "Azshara", azshara
  [207] = {"달라란", "kr"}, -- "Dalaran", dalaran
  [210] = {"듀로탄", "kr"}, -- "Durotan", durotan
  [211] = {"노르간논", "kr"}, -- "Norgannon", norgannon
  [212] = {"가로나", "kr"}, -- "Garona", garona
  [214] = {"윈드러너", "kr"}, -- "Windrunner", windrunner
  [215] = {"굴단", "kr"}, -- "Gul'dan", guldan
  [258] = {"알렉스트라자", "kr"}, -- "Alexstrasza", alexstrasza
  [264] = {"말퓨리온", "kr"}, -- "Malfurion", malfurion
  [293] = {"헬스크림", "kr"}, -- "Hellscream", hellscream
  [500] = {"Aggramar", "eu"}, -- "Aggramar", aggramar
  [501] = {"Arathor", "eu"}, -- "Arathor", arathor
  [502] = {"Aszune", "eu"}, -- "Aszune", aszune
  [503] = {"Azjol-Nerub", "eu"}, -- "Azjol-Nerub", azjolnerub
  [504] = {"Bloodhoof", "eu"}, -- "Bloodhoof", bloodhoof
  [505] = {"Doomhammer", "eu"}, -- "Doomhammer", doomhammer
  [506] = {"Draenor", "eu"}, -- "Draenor", draenor
  [507] = {"Dragonblight", "eu"}, -- "Dragonblight", dragonblight
  [508] = {"Emerald Dream", "eu"}, -- "Emerald Dream", emerald-dream
  [509] = {"Garona", "eu"}, -- "Garona", garona
  [510] = {"Vol'jin", "eu"}, -- "Vol'jin", voljin
  [511] = {"Sunstrider", "eu"}, -- "Sunstrider", sunstrider
  [512] = {"Arak-arahm", "eu"}, -- "Arak-arahm", arakarahm
  [513] = {"Twilight's Hammer", "eu"}, -- "Twilight's Hammer", twilights-hammer
  [515] = {"Zenedar", "eu"}, -- "Zenedar", zenedar
  [516] = {"Forscherliga", "eu"}, -- "Forscherliga", forscherliga
  [517] = {"Medivh", "eu"}, -- "Medivh", medivh
  [518] = {"Agamaggan", "eu"}, -- "Agamaggan", agamaggan
  [519] = {"Al'Akir", "eu"}, -- "Al'Akir", alakir
  [521] = {"Bladefist", "eu"}, -- "Bladefist", bladefist
  [522] = {"Bloodscalp", "eu"}, -- "Bloodscalp", bloodscalp
  [523] = {"Burning Blade", "eu"}, -- "Burning Blade", burning-blade
  [524] = {"Burning Legion", "eu"}, -- "Burning Legion", burning-legion
  [525] = {"Crushridge", "eu"}, -- "Crushridge", crushridge
  [526] = {"Daggerspine", "eu"}, -- "Daggerspine", daggerspine
  [527] = {"Deathwing", "eu"}, -- "Deathwing", deathwing
  [528] = {"Dragonmaw", "eu"}, -- "Dragonmaw", dragonmaw
  [529] = {"Dunemaul", "eu"}, -- "Dunemaul", dunemaul
  [531] = {"Dethecus", "eu"}, -- "Dethecus", dethecus
  [533] = {"Sinstralis", "eu"}, -- "Sinstralis", sinstralis
  [535] = {"Durotan", "eu"}, -- "Durotan", durotan
  [536] = {"Argent Dawn", "eu"}, -- "Argent Dawn", argent-dawn
  [537] = {"Kirin Tor", "eu"}, -- "Kirin Tor", kirin-tor
  [538] = {"Dalaran", "eu"}, -- "Dalaran", dalaran
  [539] = {"Archimonde", "eu"}, -- "Archimonde", archimonde
  [540] = {"Elune", "eu"}, -- "Elune", elune
  [541] = {"Illidan", "eu"}, -- "Illidan", illidan
  [542] = {"Hyjal", "eu"}, -- "Hyjal", hyjal
  [543] = {"Kael'thas", "eu"}, -- "Kael'thas", kaelthas
  [544] = {"Ner'zhul", "eu"}, -- "Ner'zhul", nerzhul
  [545] = {"Cho'gall", "eu"}, -- "Cho'gall", chogall
  [546] = {"Sargeras", "eu"}, -- "Sargeras", sargeras
  [547] = {"Runetotem", "eu"}, -- "Runetotem", runetotem
  [548] = {"Shadowsong", "eu"}, -- "Shadowsong", shadowsong
  [549] = {"Silvermoon", "eu"}, -- "Silvermoon", silvermoon
  [550] = {"Stormrage", "eu"}, -- "Stormrage", stormrage
  [551] = {"Terenas", "eu"}, -- "Terenas", terenas
  [552] = {"Thunderhorn", "eu"}, -- "Thunderhorn", thunderhorn
  [553] = {"Turalyon", "eu"}, -- "Turalyon", turalyon
  [554] = {"Ravencrest", "eu"}, -- "Ravencrest", ravencrest
  [556] = {"Shattered Hand", "eu"}, -- "Shattered Hand", shattered-hand
  [557] = {"Skullcrusher", "eu"}, -- "Skullcrusher", skullcrusher
  [558] = {"Spinebreaker", "eu"}, -- "Spinebreaker", spinebreaker
  [559] = {"Stormreaver", "eu"}, -- "Stormreaver", stormreaver
  [560] = {"Stormscale", "eu"}, -- "Stormscale", stormscale
  [561] = {"Earthen Ring", "eu"}, -- "Earthen Ring", earthen-ring
  [562] = {"Alexstrasza", "eu"}, -- "Alexstrasza", alexstrasza
  [563] = {"Alleria", "eu"}, -- "Alleria", alleria
  [564] = {"Antonidas", "eu"}, -- "Antonidas", antonidas
  [565] = {"Baelgun", "eu"}, -- "Baelgun", baelgun
  [566] = {"Blackhand", "eu"}, -- "Blackhand", blackhand
  [567] = {"Gilneas", "eu"}, -- "Gilneas", gilneas
  [568] = {"Kargath", "eu"}, -- "Kargath", kargath
  [569] = {"Khaz'goroth", "eu"}, -- "Khaz'goroth", khazgoroth
  [570] = {"Lothar", "eu"}, -- "Lothar", lothar
  [571] = {"Madmortem", "eu"}, -- "Madmortem", madmortem
  [572] = {"Malfurion", "eu"}, -- "Malfurion", malfurion
  [573] = {"Zuluhed", "eu"}, -- "Zuluhed", zuluhed
  [574] = {"Nozdormu", "eu"}, -- "Nozdormu", nozdormu
  [575] = {"Perenolde", "eu"}, -- "Perenolde", perenolde
  [576] = {"Die Silberne Hand", "eu"}, -- "Die Silberne Hand", die-silberne-hand
  [577] = {"Aegwynn", "eu"}, -- "Aegwynn", aegwynn
  [578] = {"Arthas", "eu"}, -- "Arthas", arthas
  [579] = {"Azshara", "eu"}, -- "Azshara", azshara
  [580] = {"Blackmoore", "eu"}, -- "Blackmoore", blackmoore
  [581] = {"Blackrock", "eu"}, -- "Blackrock", blackrock
  [582] = {"Destromath", "eu"}, -- "Destromath", destromath
  [583] = {"Eredar", "eu"}, -- "Eredar", eredar
  [584] = {"Frostmourne", "eu"}, -- "Frostmourne", frostmourne
  [585] = {"Frostwolf", "eu"}, -- "Frostwolf", frostwolf
  [586] = {"Gorgonnash", "eu"}, -- "Gorgonnash", gorgonnash
  [587] = {"Gul'dan", "eu"}, -- "Gul'dan", guldan
  [588] = {"Kel'Thuzad", "eu"}, -- "Kel'Thuzad", kelthuzad
  [589] = {"Kil'jaeden", "eu"}, -- "Kil'jaeden", kiljaeden
  [590] = {"Mal'Ganis", "eu"}, -- "Mal'Ganis", malganis
  [591] = {"Mannoroth", "eu"}, -- "Mannoroth", mannoroth
  [592] = {"Zirkel des Cenarius", "eu"}, -- "Zirkel des Cenarius", zirkel-des-cenarius
  [593] = {"Proudmoore", "eu"}, -- "Proudmoore", proudmoore
  [594] = {"Nathrezim", "eu"}, -- "Nathrezim", nathrezim
  [600] = {"Dun Morogh", "eu"}, -- "Dun Morogh", dun-morogh
  [601] = {"Aman'Thul", "eu"}, -- "Aman'Thul", amanthul
  [602] = {"Sen'jin", "eu"}, -- "Sen'jin", senjin
  [604] = {"Thrall", "eu"}, -- "Thrall", thrall
  [605] = {"Theradras", "eu"}, -- "Theradras", theradras
  [606] = {"Genjuros", "eu"}, -- "Genjuros", genjuros
  [607] = {"Balnazzar", "eu"}, -- "Balnazzar", balnazzar
  [608] = {"Anub'arak", "eu"}, -- "Anub'arak", anubarak
  [609] = {"Wrathbringer", "eu"}, -- "Wrathbringer", wrathbringer
  [610] = {"Onyxia", "eu"}, -- "Onyxia", onyxia
  [611] = {"Nera'thor", "eu"}, -- "Nera'thor", nerathor
  [612] = {"Nefarian", "eu"}, -- "Nefarian", nefarian
  [613] = {"Kult der Verdammten", "eu"}, -- "Kult der Verdammten", kult-der-verdammten
  [614] = {"Das Syndikat", "eu"}, -- "Das Syndikat", das-syndikat
  [615] = {"Terrordar", "eu"}, -- "Terrordar", terrordar
  [616] = {"Krag'jin", "eu"}, -- "Krag'jin", kragjin
  [617] = {"Der Rat von Dalaran", "eu"}, -- "Der Rat von Dalaran", der-rat-von-dalaran
  [618] = {"Nordrassil", "eu"}, -- "Nordrassil", nordrassil
  [619] = {"Hellscream", "eu"}, -- "Hellscream", hellscream
  [621] = {"Laughing Skull", "eu"}, -- "Laughing Skull", laughing-skull
  [622] = {"Magtheridon", "eu"}, -- "Magtheridon", magtheridon
  [623] = {"Quel'Thalas", "eu"}, -- "Quel'Thalas", quelthalas
  [624] = {"Neptulon", "eu"}, -- "Neptulon", neptulon
  [625] = {"Twisting Nether", "eu"}, -- "Twisting Nether", twisting-nether
  [626] = {"Ragnaros", "eu"}, -- "Ragnaros", ragnaros
  [627] = {"The Maelstrom", "eu"}, -- "The Maelstrom", the-maelstrom
  [628] = {"Sylvanas", "eu"}, -- "Sylvanas", sylvanas
  [629] = {"Vashj", "eu"}, -- "Vashj", vashj
  [630] = {"Bloodfeather", "eu"}, -- "Bloodfeather", bloodfeather
  [631] = {"Darksorrow", "eu"}, -- "Darksorrow", darksorrow
  [632] = {"Frostwhisper", "eu"}, -- "Frostwhisper", frostwhisper
  [633] = {"Kor'gall", "eu"}, -- "Kor'gall", korgall
  [635] = {"Defias Brotherhood", "eu"}, -- "Defias Brotherhood", defias-brotherhood
  [636] = {"The Venture Co", "eu"}, -- "The Venture Co", the-venture-co
  [637] = {"Lightning's Blade", "eu"}, -- "Lightning's Blade", lightnings-blade
  [638] = {"Haomarush", "eu"}, -- "Haomarush", haomarush
  [639] = {"Xavius", "eu"}, -- "Xavius", xavius
  [640] = {"Khaz Modan", "eu"}, -- "Khaz Modan", khaz-modan
  [641] = {"Drek'Thar", "eu"}, -- "Drek'Thar", drekthar
  [642] = {"Rashgarroth", "eu"}, -- "Rashgarroth", rashgarroth
  [643] = {"Throk'Feroth", "eu"}, -- "Throk'Feroth", throkferoth
  [644] = {"Conseil des Ombres", "eu"}, -- "Conseil des Ombres", conseil-des-ombres
  [645] = {"Varimathras", "eu"}, -- "Varimathras", varimathras
  [646] = {"Hakkar", "eu"}, -- "Hakkar", hakkar
  [647] = {"Les Sentinelles", "eu"}, -- "Les Sentinelles", les-sentinelles
  [963] = {"暗影之月", "tw"}, -- "Shadowmoon", shadowmoon
  [964] = {"尖石", "tw"}, -- "Spirestone", spirestone
  [965] = {"雷鱗", "tw"}, -- "Stormscale", stormscale
  [966] = {"巨龍之喉", "tw"}, -- "Dragonmaw", dragonmaw
  [977] = {"冰霜之刺", "tw"}, -- "Frostmane", frostmane
  [978] = {"日落沼澤", "tw"}, -- "Sundown Marsh", sundown-marsh
  [979] = {"地獄吼", "tw"}, -- "Hellscream", hellscream
  [980] = {"天空之牆", "tw"}, -- "Skywall", skywall
  [982] = {"世界之樹", "tw"}, -- "World Tree", world-tree
  [985] = {"水晶之刺", "tw"}, -- "Crystalpine Stinger", crystalpine-stinger
  [999] = {"狂熱之刃", "tw"}, -- "Zealot Blade", zealot-blade
  [1001] = {"冰風崗哨", "tw"}, -- "Chillwind Point", chillwind-point
  [1006] = {"米奈希爾", "tw"}, -- "Menethil", menethil
  [1023] = {"屠魔山谷", "tw"}, -- "Demon Fall Canyon", demon-fall-canyon
  [1033] = {"語風", "tw"}, -- "Whisperwind", whisperwind
  [1037] = {"血之谷", "tw"}, -- "Bleeding Hollow", bleeding-hollow
  [1038] = {"亞雷戈斯", "tw"}, -- "Arygos", arygos
  [1043] = {"夜空之歌", "tw"}, -- "Nightsong", nightsong
  [1046] = {"聖光之願", "tw"}, -- "Light's Hope", lights-hope
  [1048] = {"銀翼要塞", "tw"}, -- "Silverwing Hold", silverwing-hold
  [1049] = {"憤怒使者", "tw"}, -- "Wrathbringer", wrathbringer
  [1054] = {"阿薩斯", "tw"}, -- "Arthas", arthas
  [1056] = {"眾星之子", "tw"}, -- "Quel'dorei", queldorei
  [1057] = {"寒冰皇冠", "tw"}, -- "Icecrown", icecrown
  [1067] = {"Cho'gall", "us"}, -- "Cho'gall", chogall
  [1068] = {"Gul'dan", "us"}, -- "Gul'dan", guldan
  [1069] = {"Kael'thas", "us"}, -- "Kael'thas", kaelthas
  [1070] = {"Alexstrasza", "us"}, -- "Alexstrasza", alexstrasza
  [1071] = {"Kirin Tor", "us"}, -- "Kirin Tor", kirin-tor
  [1072] = {"Ravencrest", "us"}, -- "Ravencrest", ravencrest
  [1075] = {"Balnazzar", "us"}, -- "Balnazzar", balnazzar
  [1080] = {"Khadgar", "eu"}, -- "Khadgar", khadgar
  [1081] = {"Bronzebeard", "eu"}, -- "Bronzebeard", bronzebeard
  [1082] = {"Kul Tiras", "eu"}, -- "Kul Tiras", kul-tiras
  [1083] = {"Chromaggus", "eu"}, -- "Chromaggus", chromaggus
  [1084] = {"Dentarg", "eu"}, -- "Dentarg", dentarg
  [1085] = {"Moonglade", "eu"}, -- "Moonglade", moonglade
  [1086] = {"La Croisade écarlate", "eu"}, -- "La Croisade écarlate", la-croisade-écarlate
  [1087] = {"Executus", "eu"}, -- "Executus", executus
  [1088] = {"Trollbane", "eu"}, -- "Trollbane", trollbane
  [1089] = {"Mazrigos", "eu"}, -- "Mazrigos", mazrigos
  [1090] = {"Talnivarr", "eu"}, -- "Talnivarr", talnivarr
  [1091] = {"Emeriss", "eu"}, -- "Emeriss", emeriss
  [1092] = {"Drak'thul", "eu"}, -- "Drak'thul", drakthul
  [1093] = {"Ahn'Qiraj", "eu"}, -- "Ahn'Qiraj", ahnqiraj
  [1096] = {"Scarshield Legion", "eu"}, -- "Scarshield Legion", scarshield-legion
  [1097] = {"Ysera", "eu"}, -- "Ysera", ysera
  [1098] = {"Malygos", "eu"}, -- "Malygos", malygos
  [1099] = {"Rexxar", "eu"}, -- "Rexxar", rexxar
  [1104] = {"Anetheron", "eu"}, -- "Anetheron", anetheron
  [1105] = {"Nazjatar", "eu"}, -- "Nazjatar", nazjatar
  [1106] = {"Tichondrius", "eu"}, -- "Tichondrius", tichondrius
  [1117] = {"Steamwheedle Cartel", "eu"}, -- "Steamwheedle Cartel", steamwheedle-cartel
  [1118] = {"Die ewige Wacht", "eu"}, -- "Die ewige Wacht", die-ewige-wacht
  [1119] = {"Die Todeskrallen", "eu"}, -- "Die Todeskrallen", die-todeskrallen
  [1121] = {"Die Arguswacht", "eu"}, -- "Die Arguswacht", die-arguswacht
  [1122] = {"Uldaman", "eu"}, -- "Uldaman", uldaman
  [1123] = {"Eitrigg", "eu"}, -- "Eitrigg", eitrigg
  [1127] = {"Confrérie du Thorium", "eu"}, -- "Confrérie du Thorium", confrérie-du-thorium
  [1128] = {"Azshara", "us"}, -- "Azshara", azshara
  [1129] = {"Agamaggan", "us"}, -- "Agamaggan", agamaggan
  [1130] = {"Lightninghoof", "us"}, -- "Lightninghoof", lightninghoof
  [1131] = {"Nazjatar", "us"}, -- "Nazjatar", nazjatar
  [1132] = {"Malfurion", "us"}, -- "Malfurion", malfurion
  [1136] = {"Aegwynn", "us"}, -- "Aegwynn", aegwynn
  [1137] = {"Akama", "us"}, -- "Akama", akama
  [1138] = {"Chromaggus", "us"}, -- "Chromaggus", chromaggus
  [1139] = {"Draka", "us"}, -- "Draka", draka
  [1140] = {"Drak'thul", "us"}, -- "Drak'thul", drakthul
  [1141] = {"Garithos", "us"}, -- "Garithos", garithos
  [1142] = {"Hakkar", "us"}, -- "Hakkar", hakkar
  [1143] = {"Khaz Modan", "us"}, -- "Khaz Modan", khaz-modan
  [1145] = {"Mug'thol", "us"}, -- "Mug'thol", mugthol
  [1146] = {"Korgath", "us"}, -- "Korgath", korgath
  [1147] = {"Kul Tiras", "us"}, -- "Kul Tiras", kul-tiras
  [1148] = {"Malorne", "us"}, -- "Malorne", malorne
  [1151] = {"Rexxar", "us"}, -- "Rexxar", rexxar
  [1154] = {"Thorium Brotherhood", "us"}, -- "Thorium Brotherhood", thorium-brotherhood
  [1165] = {"Arathor", "us"}, -- "Arathor", arathor
  [1173] = {"Madoran", "us"}, -- "Madoran", madoran
  [1175] = {"Trollbane", "us"}, -- "Trollbane", trollbane
  [1182] = {"Muradin", "us"}, -- "Muradin", muradin
  [1184] = {"Vek'nilash", "us"}, -- "Vek'nilash", veknilash
  [1185] = {"Sen'jin", "us"}, -- "Sen'jin", senjin
  [1190] = {"Baelgun", "us"}, -- "Baelgun", baelgun
  [1258] = {"Duskwood", "us"}, -- "Duskwood", duskwood
  [1259] = {"Zuluhed", "us"}, -- "Zuluhed", zuluhed
  [1260] = {"Steamwheedle Cartel", "us"}, -- "Steamwheedle Cartel", steamwheedle-cartel
  [1262] = {"Norgannon", "us"}, -- "Norgannon", norgannon
  [1263] = {"Thrall", "us"}, -- "Thrall", thrall
  [1264] = {"Anetheron", "us"}, -- "Anetheron", anetheron
  [1265] = {"Turalyon", "us"}, -- "Turalyon", turalyon
  [1266] = {"Haomarush", "us"}, -- "Haomarush", haomarush
  [1267] = {"Scilla", "us"}, -- "Scilla", scilla
  [1268] = {"Ysondre", "us"}, -- "Ysondre", ysondre
  [1270] = {"Ysera", "us"}, -- "Ysera", ysera
  [1271] = {"Dentarg", "us"}, -- "Dentarg", dentarg
  [1276] = {"Andorhal", "us"}, -- "Andorhal", andorhal
  [1277] = {"Executus", "us"}, -- "Executus", executus
  [1278] = {"Dalvengyr", "us"}, -- "Dalvengyr", dalvengyr
  [1280] = {"Black Dragonflight", "us"}, -- "Black Dragonflight", black-dragonflight
  [1282] = {"Altar of Storms", "us"}, -- "Altar of Storms", altar-of-storms
  [1283] = {"Uldaman", "us"}, -- "Uldaman", uldaman
  [1284] = {"Aerie Peak", "us"}, -- "Aerie Peak", aerie-peak
  [1285] = {"Onyxia", "us"}, -- "Onyxia", onyxia
  [1286] = {"Demon Soul", "us"}, -- "Demon Soul", demon-soul
  [1287] = {"Gnomeregan", "us"}, -- "Gnomeregan", gnomeregan
  [1288] = {"Anvilmar", "us"}, -- "Anvilmar", anvilmar
  [1289] = {"The Venture Co", "us"}, -- "The Venture Co", the-venture-co
  [1290] = {"Sentinels", "us"}, -- "Sentinels", sentinels
  [1291] = {"Jaedenar", "us"}, -- "Jaedenar", jaedenar
  [1292] = {"Tanaris", "us"}, -- "Tanaris", tanaris
  [1293] = {"Alterac Mountains", "us"}, -- "Alterac Mountains", alterac-mountains
  [1294] = {"Undermine", "us"}, -- "Undermine", undermine
  [1295] = {"Lethon", "us"}, -- "Lethon", lethon
  [1296] = {"Blackwing Lair", "us"}, -- "Blackwing Lair", blackwing-lair
  [1297] = {"Arygos", "us"}, -- "Arygos", arygos
  [1298] = {"Vek'nilash", "eu"}, -- "Vek'nilash", veknilash
  [1299] = {"Boulderfist", "eu"}, -- "Boulderfist", boulderfist
  [1300] = {"Frostmane", "eu"}, -- "Frostmane", frostmane
  [1301] = {"Outland", "eu"}, -- "Outland", outland
  [1303] = {"Grim Batol", "eu"}, -- "Grim Batol", grim-batol
  [1304] = {"Jaedenar", "eu"}, -- "Jaedenar", jaedenar
  [1305] = {"Kazzak", "eu"}, -- "Kazzak", kazzak
  [1306] = {"Tarren Mill", "eu"}, -- "Tarren Mill", tarren-mill
  [1307] = {"Chamber of Aspects", "eu"}, -- "Chamber of Aspects", chamber-of-aspects
  [1308] = {"Ravenholdt", "eu"}, -- "Ravenholdt", ravenholdt
  [1309] = {"Well of Eternity", "eu"}, -- "Pozzo dell'Eternità", pozzo-delleternità
  [1310] = {"Eonar", "eu"}, -- "Eonar", eonar
  [1311] = {"Kilrogg", "eu"}, -- "Kilrogg", kilrogg
  [1312] = {"Aerie Peak", "eu"}, -- "Aerie Peak", aerie-peak
  [1313] = {"Wildhammer", "eu"}, -- "Wildhammer", wildhammer
  [1314] = {"Saurfang", "eu"}, -- "Saurfang", saurfang
  [1316] = {"Nemesis", "eu"}, -- "Nemesis", nemesis
  [1317] = {"Darkmoon Faire", "eu"}, -- "Darkmoon Faire", darkmoon-faire
  [1318] = {"Vek'lor", "eu"}, -- "Vek'lor", veklor
  [1319] = {"Mug'thol", "eu"}, -- "Mug'thol", mugthol
  [1320] = {"Taerar", "eu"}, -- "Taerar", taerar
  [1321] = {"Dalvengyr", "eu"}, -- "Dalvengyr", dalvengyr
  [1322] = {"Rajaxx", "eu"}, -- "Rajaxx", rajaxx
  [1323] = {"Ulduar", "eu"}, -- "Ulduar", ulduar
  [1324] = {"Malorne", "eu"}, -- "Malorne", malorne
  [1326] = {"Der abyssische Rat", "eu"}, -- "Der abyssische Rat", der-abyssische-rat
  [1327] = {"Der Mithrilorden", "eu"}, -- "Der Mithrilorden", der-mithrilorden
  [1328] = {"Tirion", "eu"}, -- "Tirion", tirion
  [1330] = {"Ambossar", "eu"}, -- "Ambossar", ambossar
  [1331] = {"Suramar", "eu"}, -- "Suramar", suramar
  [1332] = {"Krasus", "eu"}, -- "Krasus", krasus
  [1333] = {"Die Nachtwache", "eu"}, -- "Die Nachtwache", die-nachtwache
  [1334] = {"Arathi", "eu"}, -- "Arathi", arathi
  [1335] = {"Ysondre", "eu"}, -- "Ysondre", ysondre
  [1336] = {"Eldre'Thalas", "eu"}, -- "Eldre'Thalas", eldrethalas
  [1337] = {"Culte de la Rive noire", "eu"}, -- "Culte de la Rive noire", culte-de-la-rive-noire
  [1342] = {"Echo Isles", "us"}, -- "Echo Isles", echo-isles
  [1344] = {"The Forgotten Coast", "us"}, -- "The Forgotten Coast", the-forgotten-coast
  [1345] = {"Fenris", "us"}, -- "Fenris", fenris
  [1346] = {"Anub'arak", "us"}, -- "Anub'arak", anubarak
  [1347] = {"Blackwater Raiders", "us"}, -- "Blackwater Raiders", blackwater-raiders
  [1348] = {"Vashj", "us"}, -- "Vashj", vashj
  [1349] = {"Korialstrasz", "us"}, -- "Korialstrasz", korialstrasz
  [1350] = {"Misha", "us"}, -- "Misha", misha
  [1351] = {"Darrowmere", "us"}, -- "Darrowmere", darrowmere
  [1352] = {"Ravenholdt", "us"}, -- "Ravenholdt", ravenholdt
  [1353] = {"Bladefist", "us"}, -- "Bladefist", bladefist
  [1354] = {"Shu'halo", "us"}, -- "Shu'halo", shuhalo
  [1355] = {"Winterhoof", "us"}, -- "Winterhoof", winterhoof
  [1356] = {"Sisters of Elune", "us"}, -- "Sisters of Elune", sisters-of-elune
  [1357] = {"Maiev", "us"}, -- "Maiev", maiev
  [1358] = {"Rivendare", "us"}, -- "Rivendare", rivendare
  [1359] = {"Nordrassil", "us"}, -- "Nordrassil", nordrassil
  [1360] = {"Tortheldrin", "us"}, -- "Tortheldrin", tortheldrin
  [1361] = {"Cairne", "us"}, -- "Cairne", cairne
  [1362] = {"Drak'Tharon", "us"}, -- "Drak'Tharon", draktharon
  [1363] = {"Antonidas", "us"}, -- "Antonidas", antonidas
  [1364] = {"Shandris", "us"}, -- "Shandris", shandris
  [1365] = {"Moon Guard", "us"}, -- "Moon Guard", moon-guard
  [1367] = {"Nazgrel", "us"}, -- "Nazgrel", nazgrel
  [1368] = {"Hydraxis", "us"}, -- "Hydraxis", hydraxis
  [1369] = {"Wyrmrest Accord", "us"}, -- "Wyrmrest Accord", wyrmrest-accord
  [1370] = {"Farstriders", "us"}, -- "Farstriders", farstriders
  [1371] = {"Borean Tundra", "us"}, -- "Borean Tundra", borean-tundra
  [1372] = {"Quel'dorei", "us"}, -- "Quel'dorei", queldorei
  [1373] = {"Garrosh", "us"}, -- "Garrosh", garrosh
  [1374] = {"Mok'Nathal", "us"}, -- "Mok'Nathal", moknathal
  [1375] = {"Nesingwary", "us"}, -- "Nesingwary", nesingwary
  [1377] = {"Drenden", "us"}, -- "Drenden", drenden
  [1378] = {"Dun Modr", "eu"}, -- "Dun Modr", dun-modr
  [1379] = {"Zul'jin", "eu"}, -- "Zul'jin", zuljin
  [1380] = {"Uldum", "eu"}, -- "Uldum", uldum
  [1381] = {"C'Thun", "eu"}, -- "C'Thun", cthun
  [1382] = {"Sanguino", "eu"}, -- "Sanguino", sanguino
  [1383] = {"Shen'dralar", "eu"}, -- "Shen'dralar", shendralar
  [1384] = {"Tyrande", "eu"}, -- "Tyrande", tyrande
  [1385] = {"Exodar", "eu"}, -- "Exodar", exodar
  [1386] = {"Minahonda", "eu"}, -- "Minahonda", minahonda
  [1387] = {"Los Errantes", "eu"}, -- "Los Errantes", los-errantes
  [1388] = {"Lightbringer", "eu"}, -- "Lightbringer", lightbringer
  [1389] = {"Darkspear", "eu"}, -- "Darkspear", darkspear
  [1391] = {"Alonsus", "eu"}, -- "Alonsus", alonsus
  [1392] = {"Burning Steppes", "eu"}, -- "Burning Steppes", burning-steppes
  [1393] = {"Bronze Dragonflight", "eu"}, -- "Bronze Dragonflight", bronze-dragonflight
  [1394] = {"Anachronos", "eu"}, -- "Anachronos", anachronos
  [1395] = {"Colinas Pardas", "eu"}, -- "Colinas Pardas", colinas-pardas
  [1400] = {"Un'Goro", "eu"}, -- "Un'Goro", ungoro
  [1401] = {"Garrosh", "eu"}, -- "Garrosh", garrosh
  [1404] = {"Area 52", "eu"}, -- "Area 52", area-52
  [1405] = {"Todeswache", "eu"}, -- "Todeswache", todeswache
  [1406] = {"Arygos", "eu"}, -- "Arygos", arygos
  [1407] = {"Teldrassil", "eu"}, -- "Teldrassil", teldrassil
  [1408] = {"Norgannon", "eu"}, -- "Norgannon", norgannon
  [1409] = {"Lordaeron", "eu"}, -- "Lordaeron", lordaeron
  [1413] = {"Aggra (Português)", "eu"}, -- "Aggra (Português)", aggra-português
  [1415] = {"Terokkar", "eu"}, -- "Terokkar", terokkar
  [1416] = {"Blade's Edge", "eu"}, -- "Blade's Edge", blades-edge
  [1417] = {"Azuremyst", "eu"}, -- "Azuremyst", azuremyst
  [1425] = {"Drakkari", "us"}, -- "Drakkari", drakkari
  [1427] = {"Ragnaros", "us"}, -- "Ragnaros", ragnaros
  [1428] = {"Quel'Thalas", "us"}, -- "Quel'Thalas", quelthalas
  [1549] = {"Azuremyst", "us"}, -- "Azuremyst", azuremyst
  [1555] = {"Auchindoun", "us"}, -- "Auchindoun", auchindoun
  [1556] = {"Coilfang", "us"}, -- "Coilfang", coilfang
  [1557] = {"Shattered Halls", "us"}, -- "Shattered Halls", shattered-halls
  [1558] = {"Blood Furnace", "us"}, -- "Blood Furnace", blood-furnace
  [1559] = {"The Underbog", "us"}, -- "The Underbog", the-underbog
  [1563] = {"Terokkar", "us"}, -- "Terokkar", terokkar
  [1564] = {"Blade's Edge", "us"}, -- "Blade's Edge", blades-edge
  [1565] = {"Exodar", "us"}, -- "Exodar", exodar
  [1566] = {"Area 52", "us"}, -- "Area 52", area-52
  [1567] = {"Velen", "us"}, -- "Velen", velen
  [1570] = {"The Scryers", "us"}, -- "The Scryers", the-scryers
  [1572] = {"Zangarmarsh", "us"}, -- "Zangarmarsh", zangarmarsh
  [1576] = {"Fizzcrank", "us"}, -- "Fizzcrank", fizzcrank
  [1578] = {"Ghostlands", "us"}, -- "Ghostlands", ghostlands
  [1579] = {"Grizzly Hills", "us"}, -- "Grizzly Hills", grizzly-hills
  [1581] = {"Galakrond", "us"}, -- "Galakrond", galakrond
  [1582] = {"Dawnbringer", "us"}, -- "Dawnbringer", dawnbringer
  [1587] = {"Hellfire", "eu"}, -- "Hellfire", hellfire
  [1588] = {"Ghostlands", "eu"}, -- "Ghostlands", ghostlands
  [1589] = {"Nagrand", "eu"}, -- "Nagrand", nagrand
  [1595] = {"The Sha'tar", "eu"}, -- "The Sha'tar", the-shatar
  [1596] = {"Karazhan", "eu"}, -- "Karazhan", karazhan
  [1597] = {"Auchindoun", "eu"}, -- "Auchindoun", auchindoun
  [1598] = {"Shattered Halls", "eu"}, -- "Shattered Halls", shattered-halls
  [1602] = {"Гордунни", "eu"}, -- "Gordunni", gordunni
  [1603] = {"Король-лич", "eu"}, -- "Lich King", lich-king
  [1604] = {"Свежеватель Душ", "eu"}, -- "Soulflayer", soulflayer
  [1605] = {"Страж Смерти", "eu"}, -- "Deathguard", deathguard
  [1606] = {"Sporeggar", "eu"}, -- "Sporeggar", sporeggar
  [1607] = {"Nethersturm", "eu"}, -- "Nethersturm", nethersturm
  [1608] = {"Shattrath", "eu"}, -- "Shattrath", shattrath
  [1609] = {"Подземье", "eu"}, -- "Deepholm", deepholm
  [1610] = {"Седогрив", "eu"}, -- "Greymane", greymane
  [1611] = {"Festung der Stürme", "eu"}, -- "Festung der Stürme", festung-der-stürme
  [1612] = {"Echsenkessel", "eu"}, -- "Echsenkessel", echsenkessel
  [1613] = {"Blutkessel", "eu"}, -- "Blutkessel", blutkessel
  [1614] = {"Галакронд", "eu"}, -- "Galakrond", galakrond
  [1615] = {"Ревущий фьорд", "eu"}, -- "Howling Fjord", howling-fjord
  [1616] = {"Разувий", "eu"}, -- "Razuvious", razuvious
  [1617] = {"Ткач Смерти", "eu"}, -- "Deathweaver", deathweaver
  [1618] = {"Die Aldor", "eu"}, -- "Die Aldor", die-aldor
  [1619] = {"Das Konsortium", "eu"}, -- "Das Konsortium", das-konsortium
  [1620] = {"Chants éternels", "eu"}, -- "Chants éternels", chants-éternels
  [1621] = {"Marécage de Zangar", "eu"}, -- "Marécage de Zangar", marécage-de-zangar
  [1622] = {"Temple noir", "eu"}, -- "Temple noir", temple-noir
  [1623] = {"Дракономор", "eu"}, -- "Fordragon", fordragon
  [1624] = {"Naxxramas", "eu"}, -- "Naxxramas", naxxramas
  [1625] = {"Борейская тундра", "eu"}, -- "Borean Tundra", borean-tundra
  [1626] = {"Les Clairvoyants", "eu"}, -- "Les Clairvoyants", les-clairvoyants
  [1922] = {"Азурегос", "eu"}, -- "Azuregos", azuregos
  [1923] = {"Ясеневый лес", "eu"}, -- "Ashenvale", ashenvale
  [1924] = {"Пиратская бухта", "eu"}, -- "Booty Bay", booty-bay
  [1925] = {"Вечная Песня", "eu"}, -- "Eversong", eversong
  [1926] = {"Термоштепсель", "eu"}, -- "Thermaplugg", thermaplugg
  [1927] = {"Гром", "eu"}, -- "Grom", grom
  [1928] = {"Голдринн", "eu"}, -- "Goldrinn", goldrinn
  [1929] = {"Черный Шрам", "eu"}, -- "Blackscar", blackscar
  [2075] = {"雲蛟衛", "tw"}, -- "Order of the Cloud Serpent", order-of-the-cloud-serpent
  [2079] = {"와일드해머", "kr"}, -- "Wildhammer", wildhammer
  [2106] = {"렉사르", "kr"}, -- "Rexxar", rexxar
  [2107] = {"하이잘", "kr"}, -- "Hyjal", hyjal
  [2108] = {"데스윙", "kr"}, -- "Deathwing", deathwing
  [2110] = {"세나리우스", "kr"}, -- "Cenarius", cenarius
  [2111] = {"스톰레이지", "kr"}, -- "Stormrage", stormrage
  [2116] = {"줄진", "kr"}, -- "Zul'jin", zuljin
  [3207] = {"Goldrinn", "us"}, -- "Goldrinn", goldrinn
  [3208] = {"Nemesis", "us"}, -- "Nemesis", nemesis
  [3209] = {"Azralon", "us"}, -- "Azralon", azralon
  [3210] = {"Tol Barad", "us"}, -- "Tol Barad", tol-barad
  [3234] = {"Gallywix", "us"}, -- "Gallywix", gallywix
  [3721] = {"Caelestrasz", "us"}, -- "Caelestrasz", caelestrasz
  [3722] = {"Aman'Thul", "us"}, -- "Aman'Thul", amanthul
  [3723] = {"Barthilas", "us"}, -- "Barthilas", barthilas
  [3724] = {"Thaurissan", "us"}, -- "Thaurissan", thaurissan
  [3725] = {"Frostmourne", "us"}, -- "Frostmourne", frostmourne
  [3726] = {"Khaz'goroth", "us"}, -- "Khaz'goroth", khazgoroth
  [3733] = {"Dreadmaul", "us"}, -- "Dreadmaul", dreadmaul
  [3734] = {"Nagrand", "us"}, -- "Nagrand", nagrand
  [3735] = {"Dath'Remar", "us"}, -- "Dath'Remar", dathremar
  [3736] = {"Jubei'Thos", "us"}, -- "Jubei'Thos", jubeithos
  [3737] = {"Gundrak", "us"}, -- "Gundrak", gundrak
  [3738] = {"Saurfang", "us"}, -- "Saurfang", saurfang
}
-- end of generated realm list
